Fixing Writing the result of evaluated expressions example
In the current example "Writing the result of evaluated expressions" for "VERSIONS", the example is missing a single quote at the end of the line. This is causing an error when that line is evaluated.

SyntaxError: Unexpected token ILLEGAL
    at Preprocessor.evaluate (/usr/local/lib/node_modules/preprocessor/Preprocessor.js:170:25)